name: xAuth
version: 2.4.4
description: Advanced Authentication Plugin
author: [CypherX, lycano]
website: https://github.com/lycano/xAuth
main: de.luricos.bukkit.xAuth.xAuth
softdepend: [PermissionsEx, Essentials, GroupManager]

commands:
  register:
    description: Register your player with the supplied password.
    usage: /<command> <password> [email]
  login:
    description: Authenticate yourself as the owner of this player.
    aliases: [l]
    usage: /<command> <password>
  logout:
    description: Manually end your login session.
    usage: /<command>
  quit:
    description: Manually quit your session.
    aliases: [q]
    usage: /<command>
  changepw:
    description: Change your password.
    aliases: [changepassword, changepass, cpw]
    usage: /<command> <old password> <new password>
  xauth:
    description: Access all xAuth admin commands.
    aliases: [x]
    usage: |
           /<command> register <player> <password> [email] - register a player with password and optional email
           /<command> changepw <player> <new password> - change the player's password
           /<command> resetpw <player> [pwtype] - reset the player's password so he can set it by himself. Only works when he is online. If the connection is lost the account will be locked.
           /<command> logout <player> - logout a player
           /<command> unregister <player> - unregister a player
           /<command> location set|remove [global] - set/remove a location, optionally global
           /<command> reload - reload xauth
           /<command> activate <player> - activate a player's account
           /<command> lock <player> - lock a player's account
           /<command> count <all|active|locked> - Display the number of accounts for each state
           /<command> profile <player> - show the info page for a player
           /<command> info <player> - see profile <player>
           /<command> config <node> <value> - set/get configuration nodes
           /<command> debug [INFO,FINE,FINER,FINEST] - set the debug level of the xAuth-Logger
           /<command> version - show the current version and if activated the latest available version

permissions:
  xauth.allow.player.command.register:
    description: Allows players/groups to register when new registrations are disabled.
    default: false
  xauth.allow.player.command.login:
    description: Allows players to login with their registered password.
    default: true
  xauth.allow.player.command.logout:
    description: Allows players to use the logout command.
    default: false
  xauth.allow.player.command.changepw:
    description: Allows players to change their own password.
    default: true
  xauth.allow.player.command.resetpw:
    description: Allows players to reset their password when they have the flag given by the admin command xauth resetpw
    default: true
  xauth.allow.player.command.xauth.*:
    description: Grants access to all xAuth admin commands
    children:
        xauth.allow.player.command.xauth.register: true
        xauth.allow.player.command.xauth.changepw: true
        xauth.allow.player.command.xauth.resetpw: true
        xauth.allow.player.command.xauth.logout: true
        xauth.allow.player.command.xauth.quit: true
        xauth.allow.player.command.xauth.unregister: true
        xauth.allow.player.command.xauth.location: true
        xauth.allow.player.command.xauth.reload: true
        xauth.allow.player.command.xauth.activate: true
        xauth.allow.player.command.xauth.lock: true
        xauth.allow.player.command.xauth.count: true
        xauth.allow.player.command.xauth.config: true
        xauth.allow.player.command.xauth.profile: true
        xauth.allow.player.command.xauth.debug: true
        xauth.allow.player.command.xauth.version: true
        xauth.allow.player.command.xauth.update: true
        xauth.allow.player.command.xauth.upgrade: true
        xauth.allow.player.bypass.acclimit: true
  xauth.allow.player.command.xauth.register:
    description: Allows you to register other players
    default: op
  xauth.allow.player.command.xauth.changepw:
    description: Allows changing of other players passwords
    default: op
  xauth.allow.player.command.xauth.resetpw:
    description: Allows resetting a users passwords. The player will be asked for a new one.
    default: op
  xauth.allow.player.command.xauth.logout:
    description: Allows you to end a players session
    default: op
  xauth.allow.player.command.xauth.quit:
    description: Allows you to quit the session
    default: op
  xauth.allow.player.command.xauth.unregister:
    description: Remove a players registration
    default: op
  xauth.allow.player.command.xauth.location:
    description: Set/remove the current world or global teleport location
    default: op
  xauth.allow.player.command.xauth.reload:
    description: Allows you to reload the xAuth configuration and player cache.
    default: op
  xauth.allow.player.command.xauth.activate:
    description: Allows you to activate a player's account.
    default: op
  xauth.allow.player.command.xauth.lock:
    description: Allows you to lock a player's account.
    default: op
  xauth.allow.player.command.xauth.count:
    description: Allows you to count the account states.
    default: op
  xauth.allow.player.command.xauth.config:
    description: Allows you to modify the configuration via a command.
    default: op
  xauth.allow.player.command.xauth.profile:
    description: Allows you to display a <players> profile
    default: op
  xauth.allow.player.command.xauth.debug:
    description: Allows you to change permissions debug settings
    default: op
  xauth.allow.player.command.xauth.version:
    description: Allows you to display the current version
    default: op
  xauth.allow.player.command.xauth.update:
    description: Allows you to check for an update
    default: op
  xauth.allow.player.command.xauth.upgrade:
    description: Allows you to upgrade the plugin
    default: op
  xauth.allow.player.bypass.acclimit:
    description: Allows you to bypass the account limit and register an unlimited amount of accounts.
    default: op