name: xAuth
version: 2.0.26
description: Offline-mode Authentication
author: [CypherX, lycano]
website: https://github.com/lycano/xAuth
main: com.cypherx.xauth.xAuth
softdepend: [PermissionsEx, Essentials, GroupManager]

commands:
  register:
    description: Register your player with the supplied password.
    usage: /<command> <password> [email]
  login:
    description: Authenticate yourself as the owner of this player.
    aliases: [l]
    usage: /<command> <password>
  logout:
    description: Manually end your login session.
    usage: /<command>
  quit:
    description: Manually quit your session.
    aliases: [q]
    usage: /<command>
  changepw:
    description: Change your password.
    aliases: [changepassword, changepass, cpw]
    usage: /<command> <old password> <new password>
  xauth:
    description: Access all xAuth admin commands.
    aliases: [x]
    usage: |
           /<command> register <player> <password> [email] - register a player with password and optional email
           /<command> changepw <player> <new password> - change the player's password
           /<command> logout <player> - logout a player
           /<command> unregister <player> - unregister a player
           /<command> location set|remove [global] - set/remove a location, optionally global
           /<command> reload - reload xauth
           /<command> activate <player> - activate a player's account
           /<command> lock <player> - lock a player's account
           /<command> count <all|active|locked> - Display the number of accounts for each state
           /<command> profile <player> - show the info page for a player
           /<command> info <player> - see profile <player>
           /<command> config <node> <value> - set/get configuration nodes
           /<command> debug [INFO,FINE,FINER,FINEST] - set the debug level of the xAuth-Logger
           /<command> version - show the current version and if activated the latest available version

permissions:
  xauth.register:
    description: Allows players/groups to register when new registrations are disabled.
    default: false
  xauth.admin.*:
    description: Grants access to all xAuth admin commands
    children:
        xauth.admin.register: true
        xauth.admin.changepw: true
        xauth.admin.logout: true
        xauth.admin.quit: true
        xauth.admin.unregister: true
        xauth.admin.location: true
        xauth.admin.reload: true
        xauth.admin.activate: true
        xauth.admin.count: true
        xauth.admin.lock: true
        xauth.admin.config: true
        xauth.admin.profile: true
  xauth.admin.register:
    description: Allows you to register other players
    default: op
  xauth.admin.changepw:
    description: Allows changing of other players passwords
    default: op
  xauth.admin.logout:
    description: Allows you to end a players session
    default: op
  xauth.admin.quit:
    description: Allows you to quit the session
    default: op
  xauth.admin.unregister:
    description: Remove a players registration
    default: op
  xauth.admin.location:
    description: Set/remove the current world or global teleport location
    default: op
  xauth.admin.reload:
    description: Allows you to reload the xAuth configuration and player cache.
    default: op
  xauth.admin.activate:
    description: Allows you to activate a player's account.
    default: op
  xauth.admin.count:
    description: Allows you to count the account states.
    default: op
  xauth.admin.lock:
    description: Allows you to lock a player's account.
    default: op    
  xauth.admin.config:
    description: Allows you to modify the configuration via a command.
    default: op
  xauth.admin.profile:
    description: Allows you to display a <players> profile
    default: op
  xauth.bypass.acclimit:
    description: Allows you to bypass the account limit and register an unlimited amount of accounts.
  xauth.version:
    description: Show plugin version / Remote version
    default: true