ALTER TABLE `{TABLE_ACCOUNT}` ALTER COLUMN `registerip` VARCHAR(39) NULL;
ALTER TABLE `{TABLE_ACCOUNT}` ALTER COLUMN `lastloginip` VARCHAR(39) NULL;
ALTER TABLE `{TABLE_SESSION}` ALTER COLUMN `host` VARCHAR(39) NOT NULL;
ALTER TABLE `{TABLE_STRIKE}` ALTER COLUMN `host` VARCHAR(39) NOT NULL;