ALTER TABLE `{TABLE_INVENTORY}` ALTER COLUMN `itemid` VARCHAR NOT NULL;
ALTER TABLE `{TABLE_INVENTORY}` ALTER COLUMN `amount` VARCHAR NOT NULL;
ALTER TABLE `{TABLE_INVENTORY}` ALTER COLUMN `durability` VARCHAR NOT NULL;