ALTER TABLE `{TABLE_LOCATION}` ADD COLUMN `uid` VARCHAR(36) NOT NULL FIRST;
ALTER TABLE `{TABLE_LOCATION}` ADD COLUMN `global` TINYINT(1) NOT NULL DEFAULT 0;
UPDATE `{TABLE_LOCATION}` SET `uid` = `worldname`;
ALTER TABLE `{TABLE_LOCATION}` DROP COLUMN `worldname`;
ALTER TABLE `{TABLE_LOCATION}` ADD PRIMARY KEY (`uid`);