ALTER TABLE `{TABLE_ACCOUNT}` MODIFY `registerip` VARCHAR(39) NULL;
ALTER TABLE `{TABLE_ACCOUNT}` MODIFY `lastloginip` VARCHAR(39) NULL;
ALTER TABLE `{TABLE_SESSION}` MODIFY `host` VARCHAR(39) NOT NULL;
ALTER TABLE `{TABLE_STRIKE}` MODIFY `host` VARCHAR(39) NOT NULL;